version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minicurso
    ports:
      - "3306:3306"
    volumes:
      - sistemanotas_data:/var/lib/mysql

volumes:
  sistemanotas_data:
