spring:
  datasource:
    url: jdbc:mysql://localhost:3306/minicurso
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

logging:
  level:
    org:
      hibernate:
        SQL: debug